/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './user-profile.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../app.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../errors/error.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from '@angular/forms/src/directives/default_value_accessor';
import * as import16 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import17 from '@angular/common/src/directives/ng_class';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_control';
import * as import25 from '@angular/forms/src/directives/control_container';
var renderType_UserProfileComponent_Host:import0.RenderComponentType = (null as any);
class _View_UserProfileComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserProfileComponent_0_4:import3.UserProfileComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileComponent_Host0,renderType_UserProfileComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-as-user-profile',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserProfileComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserProfileComponent_0_4 = new import3.UserProfileComponent(this.parentInjector.get(import8.AppService),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.ErrorService));
    this._appEl_0.initComponent(this._UserProfileComponent_0_4,[],compView_0);
    compView_0.create(this._UserProfileComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UserProfileComponent) && (0 === requestNodeIndex))) { return this._UserProfileComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._UserProfileComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserProfileComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UserProfileComponent_Host === (null as any))) { (renderType_UserProfileComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_UserProfileComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserProfileComponentNgFactory:import12.ComponentFactory<import3.UserProfileComponent> = new import12.ComponentFactory<import3.UserProfileComponent>('app-as-user-profile',viewFactory_UserProfileComponent_Host0,import3.UserProfileComponent);
const styles_UserProfileComponent:any[] = [];
var renderType_UserProfileComponent:import0.RenderComponentType = (null as any);
class _View_UserProfileComponent0 extends import1.AppView<import3.UserProfileComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _FormGroupDirective_11_3:import13.FormGroupDirective;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import14.NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _DefaultValueAccessor_18_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_18_4:any[];
  _FormControlName_18_5:import16.FormControlName;
  _NgControl_18_6:any;
  _NgControlStatus_18_7:import14.NgControlStatus;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_26_4:any[];
  _FormControlName_26_5:import16.FormControlName;
  _NgControl_26_6:any;
  _NgControlStatus_26_7:import14.NgControlStatus;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _DefaultValueAccessor_40_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_40_4:any[];
  _FormControlName_40_5:import16.FormControlName;
  _NgControl_40_6:any;
  _NgControlStatus_40_7:import14.NgControlStatus;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _DefaultValueAccessor_48_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_48_4:any[];
  _FormControlName_48_5:import16.FormControlName;
  _NgControl_48_6:any;
  _NgControlStatus_48_7:import14.NgControlStatus;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _NgClass_60_3:import17.NgClass;
  _text_61:any;
  _anchor_62:any;
  /*private*/ _appEl_62:import2.AppElement;
  _TemplateRef_62_5:any;
  _NgIf_62_6:import18.NgIf;
  _text_63:any;
  _anchor_64:any;
  /*private*/ _appEl_64:import2.AppElement;
  _TemplateRef_64_5:any;
  _NgIf_64_6:import18.NgIf;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  _map_0:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileComponent0,renderType_UserProfileComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col');
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Update your details',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'br',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_4,'form',(null as any));
    this._FormGroupDirective_11_3 = new import13.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_11_4 = this._FormGroupDirective_11_3;
    this._NgControlStatusGroup_11_5 = new import14.NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','form-group');
    this._text_14 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'label',(null as any));
    this.renderer.setElementAttribute(this._el_15,'for','firstName');
    this._text_16 = this.renderer.createText(this._el_15,'First Name',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_13,'input',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','form-control');
    this.renderer.setElementAttribute(this._el_18,'formControlName','firstName');
    this.renderer.setElementAttribute(this._el_18,'id','firstName');
    this.renderer.setElementAttribute(this._el_18,'type','text');
    this._DefaultValueAccessor_18_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_18));
    this._NG_VALUE_ACCESSOR_18_4 = [this._DefaultValueAccessor_18_3];
    this._FormControlName_18_5 = new import16.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_18_4);
    this._NgControl_18_6 = this._FormControlName_18_5;
    this._NgControlStatus_18_7 = new import14.NgControlStatus(this._NgControl_18_6);
    this._text_19 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','form-group');
    this._text_22 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'label',(null as any));
    this.renderer.setElementAttribute(this._el_23,'for','lastName');
    this._text_24 = this.renderer.createText(this._el_23,'Last Name',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_21,'input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','form-control');
    this.renderer.setElementAttribute(this._el_26,'formControlName','lastName');
    this.renderer.setElementAttribute(this._el_26,'id','lastName');
    this.renderer.setElementAttribute(this._el_26,'type','text');
    this._DefaultValueAccessor_26_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_26));
    this._NG_VALUE_ACCESSOR_26_4 = [this._DefaultValueAccessor_26_3];
    this._FormControlName_26_5 = new import16.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_26_4);
    this._NgControl_26_6 = this._FormControlName_26_5;
    this._NgControlStatus_26_7 = new import14.NgControlStatus(this._NgControl_26_6);
    this._text_27 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-group');
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'div',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','hover');
    this._text_32 = this.renderer.createText(this._el_31,'!\n                    ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','tooltip');
    this._text_34 = this.renderer.createText(this._el_33,'Username can\'t be changed',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n                ',(null as any));
    this._text_36 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_29,'label',(null as any));
    this.renderer.setElementAttribute(this._el_37,'for','email');
    this._text_38 = this.renderer.createText(this._el_37,'Username',(null as any));
    this._text_39 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_29,'input',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','form-control');
    this.renderer.setElementAttribute(this._el_40,'formControlName','email');
    this.renderer.setElementAttribute(this._el_40,'id','email');
    this.renderer.setElementAttribute(this._el_40,'readonly','');
    this.renderer.setElementAttribute(this._el_40,'type','email');
    this._DefaultValueAccessor_40_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_40));
    this._NG_VALUE_ACCESSOR_40_4 = [this._DefaultValueAccessor_40_3];
    this._FormControlName_40_5 = new import16.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_40_4);
    this._NgControl_40_6 = this._FormControlName_40_5;
    this._NgControlStatus_40_7 = new import14.NgControlStatus(this._NgControl_40_6);
    this._text_41 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._text_42 = this.renderer.createText(this._el_11,'                \n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','form-group');
    this._text_44 = this.renderer.createText(this._el_43,'\n                ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'label',(null as any));
    this.renderer.setElementAttribute(this._el_45,'for','password');
    this._text_46 = this.renderer.createText(this._el_45,'Confirm Password',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n                ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_43,'input',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','form-control');
    this.renderer.setElementAttribute(this._el_48,'formControlName','password');
    this.renderer.setElementAttribute(this._el_48,'id','password');
    this.renderer.setElementAttribute(this._el_48,'type','password');
    this._DefaultValueAccessor_48_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_48));
    this._NG_VALUE_ACCESSOR_48_4 = [this._DefaultValueAccessor_48_3];
    this._FormControlName_48_5 = new import16.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_48_4);
    this._NgControl_48_6 = this._FormControlName_48_5;
    this._NgControlStatus_48_7 = new import14.NgControlStatus(this._NgControl_48_6);
    this._text_49 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._text_50 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','btn btn-warning');
    this.renderer.setElementAttribute(this._el_51,'style','float: right');
    this.renderer.setElementAttribute(this._el_51,'type','submit');
    this._text_52 = this.renderer.createText(this._el_51,'Update',(null as any));
    this._text_53 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_2,'\n    \n    ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','col');
    this.renderer.setElementAttribute(this._el_56,'style','border-left: 1px solid rgba(0,0,0,.1);');
    this._text_57 = this.renderer.createText(this._el_56,'\n        ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_56,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','card');
    this._text_59 = this.renderer.createText(this._el_58,'\n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_58,'div',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','card-header');
    this._NgClass_60_3 = new import17.NgClass(this.parentInjector.get(import20.IterableDiffers),this.parentInjector.get(import21.KeyValueDiffers),new import19.ElementRef(this._el_60),this.renderer);
    this._text_61 = this.renderer.createText(this._el_60,'\n                Status is:\n                ',(null as any));
    this._anchor_62 = this.renderer.createTemplateAnchor(this._el_60,(null as any));
    this._appEl_62 = new import2.AppElement(62,60,this,this._anchor_62);
    this._TemplateRef_62_5 = new import22.TemplateRef_(this._appEl_62,viewFactory_UserProfileComponent1);
    this._NgIf_62_6 = new import18.NgIf(this._appEl_62.vcRef,this._TemplateRef_62_5);
    this._text_63 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._anchor_64 = this.renderer.createTemplateAnchor(this._el_60,(null as any));
    this._appEl_64 = new import2.AppElement(64,60,this,this._anchor_64);
    this._TemplateRef_64_5 = new import22.TemplateRef_(this._appEl_64,viewFactory_UserProfileComponent2);
    this._NgIf_64_6 = new import18.NgIf(this._appEl_64.vcRef,this._TemplateRef_64_5);
    this._text_65 = this.renderer.createText(this._el_60,'\n            ',(null as any));
    this._text_66 = this.renderer.createText(this._el_58,'\n            ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_58,'div',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','card-block');
    this._text_68 = this.renderer.createText(this._el_67,'\n                ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_67,'p',(null as any));
    this.renderer.setElementAttribute(this._el_69,'class','card-text');
    this._text_70 = this.renderer.createText(this._el_69,'',(null as any));
    this._text_71 = this.renderer.createText(this._el_67,'\n            ',(null as any));
    this._text_72 = this.renderer.createText(this._el_58,'    \n        ',(null as any));
    this._text_73 = this.renderer.createText(this._el_56,'\n    ',(null as any));
    this._text_74 = this.renderer.createText(this._el_2,'\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_11,'ngSubmit',this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_11_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_18,'input',this.eventHandler(this._handle_input_18_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_18,'blur',this.eventHandler(this._handle_blur_18_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_26,'input',this.eventHandler(this._handle_input_26_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_26,'blur',this.eventHandler(this._handle_blur_26_1.bind(this)));
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_40,'input',this.eventHandler(this._handle_input_40_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_40,'blur',this.eventHandler(this._handle_blur_40_1.bind(this)));
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_48,'input',this.eventHandler(this._handle_input_48_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_48,'blur',this.eventHandler(this._handle_blur_48_1.bind(this)));
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'blue-header': p0,
        'warning-header': p1
      }
      ;
    });
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._anchor_62,
      this._text_63,
      this._anchor_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.DefaultValueAccessor) && (18 === requestNodeIndex))) { return this._DefaultValueAccessor_18_3; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (18 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_18_4; }
    if (((token === import16.FormControlName) && (18 === requestNodeIndex))) { return this._FormControlName_18_5; }
    if (((token === import24.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_6; }
    if (((token === import14.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_7; }
    if (((token === import15.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_4; }
    if (((token === import16.FormControlName) && (26 === requestNodeIndex))) { return this._FormControlName_26_5; }
    if (((token === import24.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_6; }
    if (((token === import14.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_7; }
    if (((token === import15.DefaultValueAccessor) && (40 === requestNodeIndex))) { return this._DefaultValueAccessor_40_3; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (40 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_40_4; }
    if (((token === import16.FormControlName) && (40 === requestNodeIndex))) { return this._FormControlName_40_5; }
    if (((token === import24.NgControl) && (40 === requestNodeIndex))) { return this._NgControl_40_6; }
    if (((token === import14.NgControlStatus) && (40 === requestNodeIndex))) { return this._NgControlStatus_40_7; }
    if (((token === import15.DefaultValueAccessor) && (48 === requestNodeIndex))) { return this._DefaultValueAccessor_48_3; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (48 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_48_4; }
    if (((token === import16.FormControlName) && (48 === requestNodeIndex))) { return this._FormControlName_48_5; }
    if (((token === import24.NgControl) && (48 === requestNodeIndex))) { return this._NgControl_48_6; }
    if (((token === import14.NgControlStatus) && (48 === requestNodeIndex))) { return this._NgControlStatus_48_7; }
    if (((token === import13.FormGroupDirective) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._FormGroupDirective_11_3; }
    if (((token === import25.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._ControlContainer_11_4; }
    if (((token === import14.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgControlStatusGroup_11_5; }
    if (((token === import22.TemplateRef) && (62 === requestNodeIndex))) { return this._TemplateRef_62_5; }
    if (((token === import18.NgIf) && (62 === requestNodeIndex))) { return this._NgIf_62_6; }
    if (((token === import22.TemplateRef) && (64 === requestNodeIndex))) { return this._TemplateRef_64_5; }
    if (((token === import18.NgIf) && (64 === requestNodeIndex))) { return this._NgIf_64_6; }
    if (((token === import17.NgClass) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._NgClass_60_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.userProfileForm;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_11_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_11_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_12:any = 'firstName';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._FormControlName_18_5.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this.context.currentUser.firstName;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._FormControlName_18_5.model = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._FormControlName_18_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_22:any = 'lastName';
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._FormControlName_26_5.name = currVal_22;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_22,currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this.context.currentUser.lastName;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._FormControlName_26_5.model = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    if ((changes !== (null as any))) { this._FormControlName_26_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_32:any = 'email';
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._FormControlName_40_5.name = currVal_32;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_32,currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this.context.currentUser.email;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._FormControlName_40_5.model = currVal_33;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_33,currVal_33);
      this._expr_33 = currVal_33;
    }
    if ((changes !== (null as any))) { this._FormControlName_40_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_42:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this._FormControlName_48_5.name = currVal_42;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_42,currVal_42);
      this._expr_42 = currVal_42;
    }
    if ((changes !== (null as any))) { this._FormControlName_48_5.ngOnChanges(changes); }
    const currVal_50:any = 'card-header';
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this._NgClass_60_3.klass = currVal_50;
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._map_0(this.context.currentUser.approved,!this.context.currentUser.approved);
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this._NgClass_60_3.ngClass = currVal_51;
      this._expr_51 = currVal_51;
    }
    if (!throwOnChange) { this._NgClass_60_3.ngDoCheck(); }
    const currVal_52:any = this.context.currentUser.approved;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this._NgIf_62_6.ngIf = currVal_52;
      this._expr_52 = currVal_52;
    }
    const currVal_53:boolean = !this.context.currentUser.approved;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this._NgIf_64_6.ngIf = currVal_53;
      this._expr_53 = currVal_53;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_11_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_11_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_11_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_11_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_14:any = this._NgControlStatus_18_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_18_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_18_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_18_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_18_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_18_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_24:any = this._NgControlStatus_26_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_26_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_26_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_26_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_26_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_26_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_34:any = this._NgControlStatus_40_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_40,'ng-untouched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_40_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_40,'ng-touched',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_40_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_40,'ng-pristine',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_40_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_40,'ng-dirty',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_40_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_40,'ng-valid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_40_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_40,'ng-invalid',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_43:any = this._NgControlStatus_48_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_48,'ng-untouched',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_48_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_48,'ng-touched',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_48_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_48,'ng-pristine',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_48_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_48,'ng-dirty',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_48_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_48,'ng-valid',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_48_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_48,'ng-invalid',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:boolean = !this.context.userProfileForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementProperty(this._el_51,'disabled',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_54:any = import4.interpolate(1,'User: ',this.context.currentUser.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setText(this._text_70,currVal_54);
      this._expr_54 = currVal_54;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_18_5.ngOnDestroy();
    this._FormControlName_26_5.ngOnDestroy();
    this._FormControlName_40_5.ngOnDestroy();
    this._FormControlName_48_5.ngOnDestroy();
  }
  private _handle_ngSubmit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onUpdate()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_11_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_18_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_18_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_18_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_26_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_40_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_40_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_40_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_40_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_48_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_48_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_48_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_48_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UserProfileComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UserProfileComponent> {
  if ((renderType_UserProfileComponent === (null as any))) { (renderType_UserProfileComponent = viewUtils.createRenderComponentType('C:/Users/Abdullah/Desktop/BSc_Computer_Science/sa/docker/assets/app/user-profile/user-profile.component.html',0,import11.ViewEncapsulation.None,styles_UserProfileComponent,{})); }
  return new _View_UserProfileComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UserProfileComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileComponent1,renderType_UserProfileComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Approved',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_UserProfileComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserProfileComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_UserProfileComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileComponent2,renderType_UserProfileComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Pending',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_UserProfileComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserProfileComponent2(viewUtils,parentInjector,declarationEl);
}