/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '@angular/http/src/http_module';
import * as import7 from '@angular/forms/src/directives';
import * as import8 from '@angular/forms/src/form_providers';
import * as import9 from '@angular/common/src/localization';
import * as import10 from '@angular/core/src/application_init';
import * as import11 from '@angular/core/src/testability/testability';
import * as import12 from '@angular/core/src/application_ref';
import * as import13 from '@angular/core/src/linker/compiler';
import * as import14 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import15 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import16 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import17 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import18 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import19 from '@angular/core/src/linker/view_utils';
import * as import20 from '@angular/platform-browser/src/browser/title';
import * as import21 from '@angular/http/src/backends/browser_xhr';
import * as import22 from '@angular/http/src/base_response_options';
import * as import23 from '@angular/http/src/backends/xhr_backend';
import * as import24 from '@angular/http/src/base_request_options';
import * as import25 from '@angular/forms/src/form_builder';
import * as import26 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import27 from '@angular/common/src/location/location';
import * as import28 from '@angular/router/src/url_tree';
import * as import29 from '@angular/router/src/router_outlet_map';
import * as import30 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import31 from './app.service';
import * as import32 from './errors/error.service';
import * as import33 from './staff/staff.service';
import * as import34 from '@angular/core/src/di/injector';
import * as import35 from './register/register.component.ngfactory';
import * as import36 from './login/login.component.ngfactory';
import * as import37 from './user-profile/user-profile.component.ngfactory';
import * as import38 from './user-address/user-address.component.ngfactory';
import * as import39 from './staff/staff.component.ngfactory';
import * as import40 from './page-not-found/page-not-found.component.ngfactory';
import * as import41 from './app.component.ngfactory';
import * as import42 from '@angular/core/src/application_tokens';
import * as import43 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import44 from '@angular/platform-browser/src/dom/events/key_events';
import * as import45 from '@angular/core/src/zone/ng_zone';
import * as import46 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import47 from '@angular/common/src/location/platform_location';
import * as import48 from '@angular/common/src/location/location_strategy';
import * as import49 from './register/register.component';
import * as import50 from './login/login.component';
import * as import51 from './user-profile/user-profile.component';
import * as import52 from './user-address/user-address.component';
import * as import53 from './staff/staff.component';
import * as import54 from './page-not-found/page-not-found.component';
import * as import55 from '@angular/router/src/router';
import * as import56 from '@angular/core/src/console';
import * as import57 from '@angular/core/src/i18n/tokens';
import * as import58 from '@angular/core/src/error_handler';
import * as import59 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import60 from '@angular/platform-browser/src/dom/animation_driver';
import * as import61 from '@angular/core/src/render/api';
import * as import62 from '@angular/core/src/security';
import * as import63 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import64 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import65 from '@angular/http/src/interfaces';
import * as import66 from '@angular/http/src/http';
import * as import67 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import68 from '@angular/router/src/router_config_loader';
import * as import69 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _HttpModule_5:import6.HttpModule;
  _InternalFormsSharedModule_6:import7.InternalFormsSharedModule;
  _ReactiveFormsModule_7:import8.ReactiveFormsModule;
  _AppModule_8:import1.AppModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import9.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ApplicationInitStatus_12:import10.ApplicationInitStatus;
  _Testability_13:import11.Testability;
  _ApplicationRef__14:import12.ApplicationRef_;
  __ApplicationRef_15:any;
  __Compiler_16:import13.Compiler;
  __APP_ID_17:any;
  __DOCUMENT_18:any;
  __HAMMER_GESTURE_CONFIG_19:import14.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_20:any[];
  __EventManager_21:import15.EventManager;
  __DomSharedStylesHost_22:import16.DomSharedStylesHost;
  __AnimationDriver_23:any;
  __DomRootRenderer_24:import17.DomRootRenderer_;
  __RootRenderer_25:any;
  __DomSanitizer_26:import18.DomSanitizerImpl;
  __Sanitizer_27:any;
  __ViewUtils_28:import19.ViewUtils;
  __IterableDiffers_29:any;
  __KeyValueDiffers_30:any;
  __SharedStylesHost_31:any;
  __Title_32:import20.Title;
  __BrowserXhr_33:import21.BrowserXhr;
  __ResponseOptions_34:import22.BaseResponseOptions;
  __XSRFStrategy_35:any;
  __XHRBackend_36:import23.XHRBackend;
  __RequestOptions_37:import24.BaseRequestOptions;
  __Http_38:any;
  __FormBuilder_39:import25.FormBuilder;
  __RadioControlRegistry_40:import26.RadioControlRegistry;
  __ROUTER_CONFIGURATION_41:any;
  __LocationStrategy_42:any;
  __Location_43:import27.Location;
  __UrlSerializer_44:import28.DefaultUrlSerializer;
  __RouterOutletMap_45:import29.RouterOutletMap;
  __NgModuleFactoryLoader_46:import30.SystemJsNgModuleLoader;
  __ROUTES_47:any[];
  __Router_48:any;
  __ActivatedRoute_49:any;
  __APP_BOOTSTRAP_LISTENER_50:any[];
  __AppService_51:import31.AppService;
  __ErrorService_52:import32.ErrorService;
  __StaffService_53:import33.StaffService;
  constructor(parent:import34.Injector) {
    super(parent,[
      import35.RegisterComponentNgFactory,
      import36.LoginComponentNgFactory,
      import37.UserProfileComponentNgFactory,
      import38.UserAddressComponentNgFactory,
      import39.StaffComponentNgFactory,
      import40.PageNotFoundComponentNgFactory,
      import41.AppComponentNgFactory
    ]
    ,[import41.AppComponentNgFactory]);
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == (null as any))) { (this.__LOCALE_ID_9 = 'en-US'); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == (null as any))) { (this.__NgLocalization_10 = new import9.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_15():any {
    if ((this.__ApplicationRef_15 == (null as any))) { (this.__ApplicationRef_15 = this._ApplicationRef__14); }
    return this.__ApplicationRef_15;
  }
  get _Compiler_16():import13.Compiler {
    if ((this.__Compiler_16 == (null as any))) { (this.__Compiler_16 = new import13.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == (null as any))) { (this.__APP_ID_17 = import42._appIdRandomProviderFactory()); }
    return this.__APP_ID_17;
  }
  get _DOCUMENT_18():any {
    if ((this.__DOCUMENT_18 == (null as any))) { (this.__DOCUMENT_18 = import4._document()); }
    return this.__DOCUMENT_18;
  }
  get _HAMMER_GESTURE_CONFIG_19():import14.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_19 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_19 = new import14.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_19;
  }
  get _EVENT_MANAGER_PLUGINS_20():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_20 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_20 = [
      new import43.DomEventsPlugin(),
      new import44.KeyEventsPlugin(),
      new import14.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_19)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_20;
  }
  get _EventManager_21():import15.EventManager {
    if ((this.__EventManager_21 == (null as any))) { (this.__EventManager_21 = new import15.EventManager(this._EVENT_MANAGER_PLUGINS_20,this.parent.get(import45.NgZone))); }
    return this.__EventManager_21;
  }
  get _DomSharedStylesHost_22():import16.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_22 == (null as any))) { (this.__DomSharedStylesHost_22 = new import16.DomSharedStylesHost(this._DOCUMENT_18)); }
    return this.__DomSharedStylesHost_22;
  }
  get _AnimationDriver_23():any {
    if ((this.__AnimationDriver_23 == (null as any))) { (this.__AnimationDriver_23 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_23;
  }
  get _DomRootRenderer_24():import17.DomRootRenderer_ {
    if ((this.__DomRootRenderer_24 == (null as any))) { (this.__DomRootRenderer_24 = new import17.DomRootRenderer_(this._DOCUMENT_18,this._EventManager_21,this._DomSharedStylesHost_22,this._AnimationDriver_23)); }
    return this.__DomRootRenderer_24;
  }
  get _RootRenderer_25():any {
    if ((this.__RootRenderer_25 == (null as any))) { (this.__RootRenderer_25 = import46._createConditionalRootRenderer(this._DomRootRenderer_24,this.parent.get(import46.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_25;
  }
  get _DomSanitizer_26():import18.DomSanitizerImpl {
    if ((this.__DomSanitizer_26 == (null as any))) { (this.__DomSanitizer_26 = new import18.DomSanitizerImpl()); }
    return this.__DomSanitizer_26;
  }
  get _Sanitizer_27():any {
    if ((this.__Sanitizer_27 == (null as any))) { (this.__Sanitizer_27 = this._DomSanitizer_26); }
    return this.__Sanitizer_27;
  }
  get _ViewUtils_28():import19.ViewUtils {
    if ((this.__ViewUtils_28 == (null as any))) { (this.__ViewUtils_28 = new import19.ViewUtils(this._RootRenderer_25,this._APP_ID_17,this._Sanitizer_27)); }
    return this.__ViewUtils_28;
  }
  get _IterableDiffers_29():any {
    if ((this.__IterableDiffers_29 == (null as any))) { (this.__IterableDiffers_29 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_29;
  }
  get _KeyValueDiffers_30():any {
    if ((this.__KeyValueDiffers_30 == (null as any))) { (this.__KeyValueDiffers_30 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_30;
  }
  get _SharedStylesHost_31():any {
    if ((this.__SharedStylesHost_31 == (null as any))) { (this.__SharedStylesHost_31 = this._DomSharedStylesHost_22); }
    return this.__SharedStylesHost_31;
  }
  get _Title_32():import20.Title {
    if ((this.__Title_32 == (null as any))) { (this.__Title_32 = new import20.Title()); }
    return this.__Title_32;
  }
  get _BrowserXhr_33():import21.BrowserXhr {
    if ((this.__BrowserXhr_33 == (null as any))) { (this.__BrowserXhr_33 = new import21.BrowserXhr()); }
    return this.__BrowserXhr_33;
  }
  get _ResponseOptions_34():import22.BaseResponseOptions {
    if ((this.__ResponseOptions_34 == (null as any))) { (this.__ResponseOptions_34 = new import22.BaseResponseOptions()); }
    return this.__ResponseOptions_34;
  }
  get _XSRFStrategy_35():any {
    if ((this.__XSRFStrategy_35 == (null as any))) { (this.__XSRFStrategy_35 = import6._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_35;
  }
  get _XHRBackend_36():import23.XHRBackend {
    if ((this.__XHRBackend_36 == (null as any))) { (this.__XHRBackend_36 = new import23.XHRBackend(this._BrowserXhr_33,this._ResponseOptions_34,this._XSRFStrategy_35)); }
    return this.__XHRBackend_36;
  }
  get _RequestOptions_37():import24.BaseRequestOptions {
    if ((this.__RequestOptions_37 == (null as any))) { (this.__RequestOptions_37 = new import24.BaseRequestOptions()); }
    return this.__RequestOptions_37;
  }
  get _Http_38():any {
    if ((this.__Http_38 == (null as any))) { (this.__Http_38 = import6.httpFactory(this._XHRBackend_36,this._RequestOptions_37)); }
    return this.__Http_38;
  }
  get _FormBuilder_39():import25.FormBuilder {
    if ((this.__FormBuilder_39 == (null as any))) { (this.__FormBuilder_39 = new import25.FormBuilder()); }
    return this.__FormBuilder_39;
  }
  get _RadioControlRegistry_40():import26.RadioControlRegistry {
    if ((this.__RadioControlRegistry_40 == (null as any))) { (this.__RadioControlRegistry_40 = new import26.RadioControlRegistry()); }
    return this.__RadioControlRegistry_40;
  }
  get _ROUTER_CONFIGURATION_41():any {
    if ((this.__ROUTER_CONFIGURATION_41 == (null as any))) { (this.__ROUTER_CONFIGURATION_41 = {}); }
    return this.__ROUTER_CONFIGURATION_41;
  }
  get _LocationStrategy_42():any {
    if ((this.__LocationStrategy_42 == (null as any))) { (this.__LocationStrategy_42 = import5.provideLocationStrategy(this.parent.get(import47.PlatformLocation),this.parent.get(import48.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_41)); }
    return this.__LocationStrategy_42;
  }
  get _Location_43():import27.Location {
    if ((this.__Location_43 == (null as any))) { (this.__Location_43 = new import27.Location(this._LocationStrategy_42)); }
    return this.__Location_43;
  }
  get _UrlSerializer_44():import28.DefaultUrlSerializer {
    if ((this.__UrlSerializer_44 == (null as any))) { (this.__UrlSerializer_44 = new import28.DefaultUrlSerializer()); }
    return this.__UrlSerializer_44;
  }
  get _RouterOutletMap_45():import29.RouterOutletMap {
    if ((this.__RouterOutletMap_45 == (null as any))) { (this.__RouterOutletMap_45 = new import29.RouterOutletMap()); }
    return this.__RouterOutletMap_45;
  }
  get _NgModuleFactoryLoader_46():import30.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_46 == (null as any))) { (this.__NgModuleFactoryLoader_46 = new import30.SystemJsNgModuleLoader(this._Compiler_16,this.parent.get(import30.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_46;
  }
  get _ROUTES_47():any[] {
      if ((this.__ROUTES_47 == (null as any))) { (this.__ROUTES_47 = [[
        {
          path: '',
          redirectTo: 'login',
          pathMatch: 'full'
        }
        ,
        {
          path: 'register',
          component: import49.RegisterComponent
        }
        ,
        {
          path: 'login',
          component: import50.LoginComponent
        }
        ,
        {
          path: 'user-profile',
          component: import51.UserProfileComponent
        }
        ,
        {
          path: 'user-address',
          component: import52.UserAddressComponent
        }
        ,
        {
          path: 'staff',
          component: import53.StaffComponent
        }
        ,
        {
          path: '**',
          component: import54.PageNotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_47;
  }
  get _Router_48():any {
    if ((this.__Router_48 == (null as any))) { (this.__Router_48 = import5.setupRouter(this._ApplicationRef_15,this._UrlSerializer_44,this._RouterOutletMap_45,this._Location_43,this,this._NgModuleFactoryLoader_46,this._Compiler_16,this._ROUTES_47,this._ROUTER_CONFIGURATION_41)); }
    return this.__Router_48;
  }
  get _ActivatedRoute_49():any {
    if ((this.__ActivatedRoute_49 == (null as any))) { (this.__ActivatedRoute_49 = import5.rootRoute(this._Router_48)); }
    return this.__ActivatedRoute_49;
  }
  get _APP_BOOTSTRAP_LISTENER_50():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_50 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_50 = [import5.initialRouterNavigation(this._Router_48,this._ROUTER_CONFIGURATION_41)]); }
    return this.__APP_BOOTSTRAP_LISTENER_50;
  }
  get _AppService_51():import31.AppService {
    if ((this.__AppService_51 == (null as any))) { (this.__AppService_51 = new import31.AppService(this._Http_38)); }
    return this.__AppService_51;
  }
  get _ErrorService_52():import32.ErrorService {
    if ((this.__ErrorService_52 == (null as any))) { (this.__ErrorService_52 = new import32.ErrorService()); }
    return this.__ErrorService_52;
  }
  get _StaffService_53():import33.StaffService {
    if ((this.__StaffService_53 == (null as any))) { (this.__StaffService_53 = new import33.StaffService(this._Http_38)); }
    return this.__StaffService_53;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import55.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._HttpModule_5 = new import6.HttpModule();
    this._InternalFormsSharedModule_6 = new import7.InternalFormsSharedModule();
    this._ReactiveFormsModule_7 = new import8.ReactiveFormsModule();
    this._AppModule_8 = new import1.AppModule();
    this._ErrorHandler_11 = import4.errorHandler();
    this._ApplicationInitStatus_12 = new import10.ApplicationInitStatus(this.parent.get(import10.APP_INITIALIZER,(null as any)));
    this._Testability_13 = new import11.Testability(this.parent.get(import45.NgZone));
    this._ApplicationRef__14 = new import12.ApplicationRef_(this.parent.get(import45.NgZone),this.parent.get(import56.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_12,this.parent.get(import11.TestabilityRegistry,(null as any)),this._Testability_13);
    return this._AppModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import6.HttpModule)) { return this._HttpModule_5; }
    if ((token === import7.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_6; }
    if ((token === import8.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import1.AppModule)) { return this._AppModule_8; }
    if ((token === import57.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import58.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import10.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import11.Testability)) { return this._Testability_13; }
    if ((token === import12.ApplicationRef_)) { return this._ApplicationRef__14; }
    if ((token === import12.ApplicationRef)) { return this._ApplicationRef_15; }
    if ((token === import13.Compiler)) { return this._Compiler_16; }
    if ((token === import42.APP_ID)) { return this._APP_ID_17; }
    if ((token === import59.DOCUMENT)) { return this._DOCUMENT_18; }
    if ((token === import14.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_19; }
    if ((token === import15.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_20; }
    if ((token === import15.EventManager)) { return this._EventManager_21; }
    if ((token === import16.DomSharedStylesHost)) { return this._DomSharedStylesHost_22; }
    if ((token === import60.AnimationDriver)) { return this._AnimationDriver_23; }
    if ((token === import17.DomRootRenderer)) { return this._DomRootRenderer_24; }
    if ((token === import61.RootRenderer)) { return this._RootRenderer_25; }
    if ((token === import18.DomSanitizer)) { return this._DomSanitizer_26; }
    if ((token === import62.Sanitizer)) { return this._Sanitizer_27; }
    if ((token === import19.ViewUtils)) { return this._ViewUtils_28; }
    if ((token === import63.IterableDiffers)) { return this._IterableDiffers_29; }
    if ((token === import64.KeyValueDiffers)) { return this._KeyValueDiffers_30; }
    if ((token === import16.SharedStylesHost)) { return this._SharedStylesHost_31; }
    if ((token === import20.Title)) { return this._Title_32; }
    if ((token === import21.BrowserXhr)) { return this._BrowserXhr_33; }
    if ((token === import22.ResponseOptions)) { return this._ResponseOptions_34; }
    if ((token === import65.XSRFStrategy)) { return this._XSRFStrategy_35; }
    if ((token === import23.XHRBackend)) { return this._XHRBackend_36; }
    if ((token === import24.RequestOptions)) { return this._RequestOptions_37; }
    if ((token === import66.Http)) { return this._Http_38; }
    if ((token === import25.FormBuilder)) { return this._FormBuilder_39; }
    if ((token === import26.RadioControlRegistry)) { return this._RadioControlRegistry_40; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_41; }
    if ((token === import48.LocationStrategy)) { return this._LocationStrategy_42; }
    if ((token === import27.Location)) { return this._Location_43; }
    if ((token === import28.UrlSerializer)) { return this._UrlSerializer_44; }
    if ((token === import29.RouterOutletMap)) { return this._RouterOutletMap_45; }
    if ((token === import67.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_46; }
    if ((token === import68.ROUTES)) { return this._ROUTES_47; }
    if ((token === import55.Router)) { return this._Router_48; }
    if ((token === import69.ActivatedRoute)) { return this._ActivatedRoute_49; }
    if ((token === import42.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_50; }
    if ((token === import31.AppService)) { return this._AppService_51; }
    if ((token === import32.ErrorService)) { return this._ErrorService_52; }
    if ((token === import33.StaffService)) { return this._StaffService_53; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__14.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);