/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './user-address.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../app.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../errors/error.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from '@angular/forms/src/directives/default_value_accessor';
import * as import16 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/control_container';
var renderType_UserAddressComponent_Host:import0.RenderComponentType = (null as any);
class _View_UserAddressComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserAddressComponent_0_4:import3.UserAddressComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserAddressComponent_Host0,renderType_UserAddressComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-as-user-address',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserAddressComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserAddressComponent_0_4 = new import3.UserAddressComponent(this.parentInjector.get(import8.AppService),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.ErrorService));
    this._appEl_0.initComponent(this._UserAddressComponent_0_4,[],compView_0);
    compView_0.create(this._UserAddressComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UserAddressComponent) && (0 === requestNodeIndex))) { return this._UserAddressComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._UserAddressComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserAddressComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UserAddressComponent_Host === (null as any))) { (renderType_UserAddressComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_UserAddressComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserAddressComponentNgFactory:import12.ComponentFactory<import3.UserAddressComponent> = new import12.ComponentFactory<import3.UserAddressComponent>('app-as-user-address',viewFactory_UserAddressComponent_Host0,import3.UserAddressComponent);
const styles_UserAddressComponent:any[] = [];
var renderType_UserAddressComponent:import0.RenderComponentType = (null as any);
class _View_UserAddressComponent0 extends import1.AppView<import3.UserAddressComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _FormGroupDirective_11_3:import13.FormGroupDirective;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import14.NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _DefaultValueAccessor_18_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_18_4:any[];
  _FormControlName_18_5:import16.FormControlName;
  _NgControl_18_6:any;
  _NgControlStatus_18_7:import14.NgControlStatus;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_26_4:any[];
  _FormControlName_26_5:import16.FormControlName;
  _NgControl_26_6:any;
  _NgControlStatus_26_7:import14.NgControlStatus;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_34_4:any[];
  _FormControlName_34_5:import16.FormControlName;
  _NgControl_34_6:any;
  _NgControlStatus_34_7:import14.NgControlStatus;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _DefaultValueAccessor_42_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_42_4:any[];
  _FormControlName_42_5:import16.FormControlName;
  _NgControl_42_6:any;
  _NgControlStatus_42_7:import14.NgControlStatus;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _anchor_52:any;
  /*private*/ _appEl_52:import2.AppElement;
  _TemplateRef_52_5:any;
  _NgFor_52_6:import17.NgFor;
  _text_53:any;
  _text_54:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserAddressComponent0,renderType_UserAddressComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col');
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Add your address',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'br',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_4,'form',(null as any));
    this._FormGroupDirective_11_3 = new import13.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_11_4 = this._FormGroupDirective_11_3;
    this._NgControlStatusGroup_11_5 = new import14.NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','form-group');
    this._text_14 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'label',(null as any));
    this.renderer.setElementAttribute(this._el_15,'for','houseNumber');
    this._text_16 = this.renderer.createText(this._el_15,'House Number',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_13,'input',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','form-control');
    this.renderer.setElementAttribute(this._el_18,'formControlName','houseNumber');
    this.renderer.setElementAttribute(this._el_18,'id','houseNumber');
    this.renderer.setElementAttribute(this._el_18,'type','text');
    this._DefaultValueAccessor_18_3 = new import15.DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_18));
    this._NG_VALUE_ACCESSOR_18_4 = [this._DefaultValueAccessor_18_3];
    this._FormControlName_18_5 = new import16.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_18_4);
    this._NgControl_18_6 = this._FormControlName_18_5;
    this._NgControlStatus_18_7 = new import14.NgControlStatus(this._NgControl_18_6);
    this._text_19 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','form-group');
    this._text_22 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'label',(null as any));
    this.renderer.setElementAttribute(this._el_23,'for','street');
    this._text_24 = this.renderer.createText(this._el_23,'Street Name',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_21,'input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','form-control');
    this.renderer.setElementAttribute(this._el_26,'formControlName','street');
    this.renderer.setElementAttribute(this._el_26,'id','street');
    this.renderer.setElementAttribute(this._el_26,'type','text');
    this._DefaultValueAccessor_26_3 = new import15.DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_26));
    this._NG_VALUE_ACCESSOR_26_4 = [this._DefaultValueAccessor_26_3];
    this._FormControlName_26_5 = new import16.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_26_4);
    this._NgControl_26_6 = this._FormControlName_26_5;
    this._NgControlStatus_26_7 = new import14.NgControlStatus(this._NgControl_26_6);
    this._text_27 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._text_28 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-group');
    this._text_30 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'label',(null as any));
    this.renderer.setElementAttribute(this._el_31,'for','city');
    this._text_32 = this.renderer.createText(this._el_31,'City',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_29,'input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','form-control');
    this.renderer.setElementAttribute(this._el_34,'formControlName','city');
    this.renderer.setElementAttribute(this._el_34,'id','city');
    this.renderer.setElementAttribute(this._el_34,'type','text');
    this._DefaultValueAccessor_34_3 = new import15.DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_34));
    this._NG_VALUE_ACCESSOR_34_4 = [this._DefaultValueAccessor_34_3];
    this._FormControlName_34_5 = new import16.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_4);
    this._NgControl_34_6 = this._FormControlName_34_5;
    this._NgControlStatus_34_7 = new import14.NgControlStatus(this._NgControl_34_6);
    this._text_35 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._text_36 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','form-group');
    this._text_38 = this.renderer.createText(this._el_37,'\n                    ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'label',(null as any));
    this.renderer.setElementAttribute(this._el_39,'for','postcode');
    this._text_40 = this.renderer.createText(this._el_39,'Postcode',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n                    ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'input',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','form-control');
    this.renderer.setElementAttribute(this._el_42,'formControlName','postcode');
    this.renderer.setElementAttribute(this._el_42,'id','postcode');
    this.renderer.setElementAttribute(this._el_42,'type','text');
    this._DefaultValueAccessor_42_3 = new import15.DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_42));
    this._NG_VALUE_ACCESSOR_42_4 = [this._DefaultValueAccessor_42_3];
    this._FormControlName_42_5 = new import16.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_42_4);
    this._NgControl_42_6 = this._FormControlName_42_5;
    this._NgControlStatus_42_7 = new import14.NgControlStatus(this._NgControl_42_6);
    this._text_43 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_45,'style','float: right');
    this.renderer.setElementAttribute(this._el_45,'type','submit');
    this._text_46 = this.renderer.createText(this._el_45,'Save',(null as any));
    this._text_47 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_49 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','col');
    this.renderer.setElementAttribute(this._el_50,'style','border-left: 1px solid rgba(0,0,0,.1);');
    this._text_51 = this.renderer.createText(this._el_50,'\n        ',(null as any));
    this._anchor_52 = this.renderer.createTemplateAnchor(this._el_50,(null as any));
    this._appEl_52 = new import2.AppElement(52,50,this,this._anchor_52);
    this._TemplateRef_52_5 = new import19.TemplateRef_(this._appEl_52,viewFactory_UserAddressComponent1);
    this._NgFor_52_6 = new import17.NgFor(this._appEl_52.vcRef,this._TemplateRef_52_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_53 = this.renderer.createText(this._el_50,'\n    ',(null as any));
    this._text_54 = this.renderer.createText(this._el_2,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_11,'ngSubmit',this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_11_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_18,'input',this.eventHandler(this._handle_input_18_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_18,'blur',this.eventHandler(this._handle_blur_18_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_26,'input',this.eventHandler(this._handle_input_26_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_26,'blur',this.eventHandler(this._handle_blur_26_1.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_34,'input',this.eventHandler(this._handle_input_34_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_34,'blur',this.eventHandler(this._handle_blur_34_1.bind(this)));
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_42,'input',this.eventHandler(this._handle_input_42_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_42,'blur',this.eventHandler(this._handle_blur_42_1.bind(this)));
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._anchor_52,
      this._text_53,
      this._text_54
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.DefaultValueAccessor) && (18 === requestNodeIndex))) { return this._DefaultValueAccessor_18_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (18 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_18_4; }
    if (((token === import16.FormControlName) && (18 === requestNodeIndex))) { return this._FormControlName_18_5; }
    if (((token === import22.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_6; }
    if (((token === import14.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_7; }
    if (((token === import15.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_4; }
    if (((token === import16.FormControlName) && (26 === requestNodeIndex))) { return this._FormControlName_26_5; }
    if (((token === import22.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_6; }
    if (((token === import14.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_7; }
    if (((token === import15.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_4; }
    if (((token === import16.FormControlName) && (34 === requestNodeIndex))) { return this._FormControlName_34_5; }
    if (((token === import22.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_6; }
    if (((token === import14.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_7; }
    if (((token === import15.DefaultValueAccessor) && (42 === requestNodeIndex))) { return this._DefaultValueAccessor_42_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_4; }
    if (((token === import16.FormControlName) && (42 === requestNodeIndex))) { return this._FormControlName_42_5; }
    if (((token === import22.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_6; }
    if (((token === import14.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_7; }
    if (((token === import13.FormGroupDirective) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._FormGroupDirective_11_3; }
    if (((token === import23.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._ControlContainer_11_4; }
    if (((token === import14.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._NgControlStatusGroup_11_5; }
    if (((token === import19.TemplateRef) && (52 === requestNodeIndex))) { return this._TemplateRef_52_5; }
    if (((token === import17.NgFor) && (52 === requestNodeIndex))) { return this._NgFor_52_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.addressForm;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_11_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_11_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_12:any = 'houseNumber';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._FormControlName_18_5.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._FormControlName_18_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_21:any = 'street';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._FormControlName_26_5.name = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._FormControlName_26_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_30:any = 'city';
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._FormControlName_34_5.name = currVal_30;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_30,currVal_30);
      this._expr_30 = currVal_30;
    }
    if ((changes !== (null as any))) { this._FormControlName_34_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_39:any = 'postcode';
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this._FormControlName_42_5.name = currVal_39;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_39,currVal_39);
      this._expr_39 = currVal_39;
    }
    if ((changes !== (null as any))) { this._FormControlName_42_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_47:any = this.context.addresses;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this._NgFor_52_6.ngForOf = currVal_47;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_47,currVal_47);
      this._expr_47 = currVal_47;
    }
    if ((changes !== (null as any))) { this._NgFor_52_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_52_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_11_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_11_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_11_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_11_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._NgControlStatus_18_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_18_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_18_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_18_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_18_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_18_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_22:any = this._NgControlStatus_26_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_26_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_26_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_26_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_26_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_26_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_31:any = this._NgControlStatus_34_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_34_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_34_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_34_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_34_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_34_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_40:any = this._NgControlStatus_42_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_42,'ng-untouched',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_42_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_42,'ng-touched',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_42_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_42,'ng-pristine',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_42_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_42,'ng-dirty',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_42_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_42,'ng-valid',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_42_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_42,'ng-invalid',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:boolean = !this.context.addressForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementProperty(this._el_45,'disabled',currVal_46);
      this._expr_46 = currVal_46;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_18_5.ngOnDestroy();
    this._FormControlName_26_5.ngOnDestroy();
    this._FormControlName_34_5.ngOnDestroy();
    this._FormControlName_42_5.ngOnDestroy();
  }
  private _handle_ngSubmit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSaveAddress()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_11_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_18_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_18_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_18_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_26_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_34_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_42_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UserAddressComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UserAddressComponent> {
  if ((renderType_UserAddressComponent === (null as any))) { (renderType_UserAddressComponent = viewUtils.createRenderComponentType('C:/Users/Abdullah/Desktop/BSc_Computer_Science/sa/docker/assets/app/user-address/user-address.component.html',0,import11.ViewEncapsulation.None,styles_UserAddressComponent,{})); }
  return new _View_UserAddressComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UserAddressComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserAddressComponent1,renderType_UserAddressComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','card');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-header blue-header');
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'p',(null as any));
    this.renderer.setElementAttribute(this._el_4,'style','padding: .5rem .75rem; margin-bottom:0;');
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','card-block');
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'br',(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'',(null as any));
    this._el_12 = this.renderer.createElement(this._el_8,'br',(null as any));
    this._text_13 = this.renderer.createText(this._el_8,'',(null as any));
    this._el_14 = this.renderer.createElement(this._el_8,'br',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','card-footer');
    this._text_18 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','btn btn-danger config');
    this.renderer.setElementAttribute(this._el_19,'type','button');
    this._text_20 = this.renderer.createText(this._el_19,'Delete',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'    \n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'Address ',(this.context.index + 1),'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'\n                House: ',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.houseNumber),'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_9,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n                Street: ',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.street),'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_11,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'\n                City: ',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.city),'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_13,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'\n                Postcode: ',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.postcode),'\n            ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_15,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onAddressDelete(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserAddressComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserAddressComponent1(viewUtils,parentInjector,declarationEl);
}