/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './header.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../app.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/router/src/directives/router_link_active';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/router/src/directives/router_link';
import * as import14 from '@angular/router/src/router';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/common/src/location/location_strategy';
import * as import18 from '@angular/core/src/security';
var renderType_HeaderComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import3.HeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-as-header',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import3.HeaderComponent(this.parentInjector.get(import8.AppService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HeaderComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeaderComponent_Host === (null as any))) { (renderType_HeaderComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_HeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeaderComponentNgFactory:import10.ComponentFactory<import3.HeaderComponent> = new import10.ComponentFactory<import3.HeaderComponent>('app-as-header',viewFactory_HeaderComponent_Host0,import3.HeaderComponent);
const styles_HeaderComponent:any[] = [];
var renderType_HeaderComponent:import0.RenderComponentType = (null as any);
class _View_HeaderComponent0 extends import1.AppView<import3.HeaderComponent> {
  _text_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _RouterLinkActive_37_3:import11.RouterLinkActive;
  _query_RouterLink_37_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_37_1:import12.QueryList<any>;
  _el_38:any;
  _RouterLinkWithHref_38_3:import13.RouterLinkWithHref;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _arr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent0,renderType_HeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'    ',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','navbar navbar-expand-lg navbar-dark bg-dark-blue fixed-top');
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','container');
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'a',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','navbar-brand');
    this.renderer.setElementAttribute(this._el_6,'href','#');
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'img',(null as any));
    this.renderer.setElementAttribute(this._el_8,'alt','');
    this.renderer.setElementAttribute(this._el_8,'height','30');
    this.renderer.setElementAttribute(this._el_8,'src','/assets/logo.png');
    this.renderer.setElementAttribute(this._el_8,'width','150');
    this._text_9 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_4,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','navbar-nav navbar-right');
    this.renderer.setElementAttribute(this._el_11,'style','flex-direction: row;');
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'li',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','nav-item ');
    this._text_14 = this.renderer.createText(this._el_13,'\n          ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'a',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','nav-link');
    this._text_16 = this.renderer.createText(this._el_15,'Orders',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_11,'li',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','nav-item');
    this._text_20 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'a',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','nav-link');
    this.renderer.setElementAttribute(this._el_21,'href','http://3amigoss.azurewebsites.net/api/products');
    this._text_22 = this.renderer.createText(this._el_21,'Products',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_11,'li',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','nav-item');
    this._text_26 = this.renderer.createText(this._el_25,'\n          ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'a',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','nav-link');
    this.renderer.setElementAttribute(this._el_27,'href','http://3amigosp.azurewebsites.net/purchasing');
    this._text_28 = this.renderer.createText(this._el_27,'Purchases',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_11,'li',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','nav-item');
    this._text_32 = this.renderer.createText(this._el_31,'\n          ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'a',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','nav-link');
    this._text_34 = this.renderer.createText(this._el_33,'Messages',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_11,'\n                  \n        ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_11,'li',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','nav-item');
    this.renderer.setElementAttribute(this._el_37,'routerLinkActive','active');
    this.renderer.setElementAttribute(this._el_37,'style','padding-right:0px');
    this._RouterLinkActive_37_3 = new import11.RouterLinkActive(this.parentInjector.get(import14.Router),new import15.ElementRef(this._el_37),this.renderer);
    this._query_RouterLink_37_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_37_1 = new import12.QueryList<any>();
    this._el_38 = this.renderer.createElement(this._el_37,'a',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','nav-link');
    this._RouterLinkWithHref_38_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._text_39 = this.renderer.createText(this._el_38,'User',(null as any));
    this._text_40 = this.renderer.createText(this._el_11,'\n      ',(null as any));
    this._text_41 = this.renderer.createText(this._el_4,'\n    \n  ',(null as any));
    this._text_42 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_43 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_38,'click',this.eventHandler(this._handle_click_38_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._RouterLinkWithHref_38_3; }
    if (((token === import11.RouterLinkActive) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._RouterLinkActive_37_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkActive_37_3.routerLinkActive = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_37_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_4:any = this._arr_0('login');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkWithHref_38_3.routerLink = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_38_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_37_0.dirty) {
        this._query_RouterLink_37_0.reset([]);
        this._RouterLinkActive_37_3.links = this._query_RouterLink_37_0;
        this._query_RouterLink_37_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_37_1.dirty) {
        this._query_RouterLinkWithHref_37_1.reset([this._RouterLinkWithHref_38_3]);
        this._RouterLinkActive_37_3.linksWithHrefs = this._query_RouterLinkWithHref_37_1;
        this._query_RouterLinkWithHref_37_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_37_3.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'http://3amigoso.azurewebsites.net/order/displayorders/?custoRef=',this.context.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_15,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'http://3amigosm.azurewebsites.net/message?custid=',this.context.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_33,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this._RouterLinkWithHref_38_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_38,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_38_3.ngOnDestroy();
    this._RouterLinkActive_37_3.ngOnDestroy();
  }
  private _handle_click_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_38_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeaderComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HeaderComponent> {
  if ((renderType_HeaderComponent === (null as any))) { (renderType_HeaderComponent = viewUtils.createRenderComponentType('C:/Users/Abdullah/Desktop/BSc_Computer_Science/sa/docker/assets/app/header/header.component.html',0,import9.ViewEncapsulation.None,styles_HeaderComponent,{})); }
  return new _View_HeaderComponent0(viewUtils,parentInjector,declarationEl);
}